### ISSUE TITLE
JSONP not always returned

### ISSUE THREAD

**Issue by brishin** [adicu/data.adicu.com#18]
See

http://data.adicu.com/courses?api_token=515abdcf27200000029ca515&course=HUMA1001&jsonp=angular&limit=10&page=1&term=20134

vs

http://data.adicu.com/courses?api_token=515abdcf27200000029ca515&course=HUMA1001&jsonp=angular&limit=10&page=1&term=20133

Only the second one is wrapped with angular(.......). Major problem, I think in parsing the response. Script stops running on some browsers?

**Comment by znewman01** [comment]
OHH i see, it's just not doing jsonp for 204s, will fix in 30s
