### ISSUE TITLE
Call Number parameter doesn't work properly

### ISSUE THREAD

**Issue by brishin** [adicu/data.adicu.com#19]
See http://data.adicu.com/courses?api_token=515abdcf27200000029ca515&callNumber=7733&jsonp=angular.callbacks._1&limit=10&page=1&term=20133

due to weird regex handling?

**Comment by brishin** [comment]
This should just return one result because I gave it a unique ID?

http://data.adicu.com/courses?api_token=515abdcf27200000029ca515&id=POLS8601G001&jsonp=angular.callbacks._0&term=20133

**Comment by znewman01** [comment]
callNumber-> call_number

**Comment by znewman01** [comment]
id -> course

**Comment by brishin** [comment]
Hmm strange. Looks good. Don't know why I had problems then. 3am coding?
