### ISSUE TITLE
HTML entities in descriptions are not escaped properly

### ISSUE THREAD

**Issue by brishin** [adicu/data.adicu.com#20]
Search for 
`&amp;` in
http://data.adicu.com/courses?api_token=515abdcf27200000029ca515&description=acting&jsonp=angular.callbacks._1&limit=10&page=1&term=20133

**Comment by znewman01** [comment]
what is the correct result here? just "&" in the result?

**Comment by brishin** [comment]
Yeah.

So

```
&amp; -> &
```

Need to evaluate those on db insert, I think.

**Comment by znewman01** [comment]
yeah, i agree that that's the time to do that
