### ISSUE TITLE
Default limit on API calls 

### ISSUE THREAD

**Issue by brishin** [adicu/data.adicu.com#22]
Right now

http://data.adicu.com/courses/v2/sections?api_token=515abdcf27200000029ca515&not_full=false&pretty=true

is giving me >200 results.

**Comment by znewman01** [comment]
The default limit is 250. The idea is that this is an upper limit, and that if people want fewer at a time they'll limit it themselves.

Maybe we should have two parameters: an upper limit (250 or so) and a default limit (20 or so)?

**Comment by brishin** [comment]
Agreed. The 250ish page weighs in at 150kb~, which is pretty big for clients to download each time anyway.
