### ISSUE TITLE
API doesn't like spaces in queries

### ISSUE THREAD

**Issue by brishin** [adicu/data.adicu.com#25]
http://data.adicu.com/courses/v2/courses?api_token=515abdcf27200000029ca515&description=lit%20hum&jsonp=angular.callbacks._0&limit=10&page=1&term=20133

**Comment by znewman01** [comment]
API should use elasticsearch internally and we should get rid of courses reliance on elasticsearch

thoughts?

**Comment by znewman01** [comment]
this will fix #25, #24

**Comment by brishin** [comment]
Agreed with using elasticsearch internally.
