### ISSUE TITLE
Many Courses have invalid information

### ISSUE THREAD

**Issue by brishin** [adicu/data.adicu.com#44]
A lot of courses look like this right now:
http://data.adicu.com/courses/v2/courses?api_token=51ffc99d0b18dc0002859b8d&course_full=SOCWT8004&jsonp=angular.callbacks._5

I previously fixed this through weighting the fields differently:
https://github.com/adicu/Courses/blob/a367aa360f6852e0426d5e13c9891f563edffec4/src/js/services/Course.coffee#L87-94

See queries at http://courses.adicu.com/beta/#/schedule
Many queries have courses with no description. These tend to also have no section information. :sweat:

**Comment by zhemao** [comment]
Yeah, that's because we're getting bad data from CUIT. Is this causing low
quality search results? If not, then I say we should just live with it.
Otherwise, I can add better data validation to the import scripts.
