### ISSUE TITLE
Courses are in search but not in the actual DB

### ISSUE THREAD

**Issue by brishin** [adicu/data.adicu.com#45]
So I'm doing a search like this:
http://data.adicu.com/courses/v2/search?api_token=51ffc99d0b18dc0002859b8d&jsonp=angular.callbacks._4&q=A&term=20141

I'm trying to get the info for the second result now: 

```
Term: [
"20141"
],
CourseTitle: "SEX, DRUGS, AND WOMEN OF COLOR",
DepartmentName: "Ctr for Ethnicity and Race",
CourseFull: "CSERW3901",
Course: "CSER3901",
DepartmentCode: "CSER",
Instructor: [
"HWAHNG, SEL J"
],
CourseSubtitle: "SEX, DRUGS, AND WOMEN OF COLOR"
```

But a search doesn't show this course in the DB:
http://data.adicu.com/courses/v2/courses?api_token=51ffc99d0b18dc0002859b8d&course_full=CSERW3901&jsonp=angular.callbacks._5

**Comment by brishin** [comment]
Another example: 
http://data.adicu.com/courses/v2/courses?api_token=51ffc99d0b18dc0002859b8d&course=BIOL4310&jsonp=angular.callbacks._5
is in the DB but is impossible to find in the search

**Comment by zhemao** [comment]
The first problem (in search but not in DB), is because my import script is only overwriting things and not deleting the old index first, which shouldn't be a difficult fix. The second issue (in DB but not in search) is more puzzling.

**Comment by zhemao** [comment]
I've fixed the problem with old no-longer existent courses showing up in search. And the course you said you couldn't find in search seems to show up now.

http://data.adicu.com/courses/v2/search?api_token=51ffc99d0b18dc0002859b8d&q=BIOL4310

I'm closing the issue for now. Feel free to reopen if you spot another inconsistency.
