### ISSUE TITLE
Associate API keys with hostnames

### ISSUE THREAD

**Issue by brishin** [adicu/data.adicu.com#61]
API token's should have a (optional?) domain name associated with them.
This will allow us to us to "whitelist" certain tokens (like Courses) to have a higher rate-limit.

**Comment by parthibanloganathan** [comment]
More details please.

@natebrennand Can you guys add more detailed descriptions to all important open issues?

**Comment by natebrennand** [comment]
I clarified some of the details, some of it we still need to decide.

Should we require a domain be associated with a token? An ideal solution might have 2 tiers of tokens but this requires a lot of added complexity on our side.
