### ISSUE TITLE
Allow filtering by query parameter

### ISSUE THREAD

**Issue by brishin** [adicu/data.adicu.com#63]
Allow API consumers to filter what options are returned by `/*/*/options/*` queries. This will involve refactoring how the [SQL query builder](https://github.com/adicu/data.adicu.com/blob/v2/data/lib/query.py) is called because currently the `WHERE` statement is [built using the config dictionary](https://github.com/adicu/data.adicu.com/blob/v2/data/lib/query.py#L25-L28).

Ex: `/housing/rooms/options/room_area?room_type=***&lottery_number=5324`

**Comment by natebrennand** [comment]
clarified
